version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: unless-stopped
    ports:
      - "5672:5672"     # AMQP
      - "15672:15672"   # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin123
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  rabbitmq_consumer:
    build: .
    container_name: consumidor-rabbit
    restart: unless-stopped
    environment:
      RABBITMQ_HOST: rabbitmq      # hostname interno do Docker
      RABBITMQ_USERNAME: admin
      RABBITMQ_PASSWORD: admin123
      WORKER_CONCURRENCY: 5
      BOT_HYBRID_FUNCTION_URL: https://gythzfdqhubzzisordgq.supabase.co/functions/v1/bot-hybrid
    depends_on:
      - rabbitmq

volumes:
  rabbitmq_data:
