version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: unless-stopped
    ports:
      - "5672:5672"   # Porta AMQP
      - "15672:15672" # Porta Management Web UI
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin123
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  rabbitmq_consumer:
    build: .
    container_name: consumidor-rabbit
    # O network_mode: "host" não é mais necessário aqui.
    # O Docker Compose gerencia a rede automaticamente.
    environment:
      # O nome do serviço 'rabbitmq' é resolvido automaticamente.
      # A porta 5672 é a padrão, então não precisa ser explícita.
      - RABBITMQ_URL=amqp://admin:admin123@rabbitmq:5672
    # Depende do serviço 'rabbitmq'
    depends_on:
      - rabbitmq
    restart: unless-stopped

volumes:
  rabbitmq_data:
