version: '3.8'

services:
  rabbitmq_consumer:
    build: .
    container_name: consumidor-rabbit
    network_mode: "host"
    environment:
      - RABBITMQ_URL=${RABBITMQ_URL}
      - RABBITMQ_USERNAME=${RABBITMQ_USERNAME}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
    restart: unless-stopped
